### ISSUE TITLE
npm run start fail

### ISSUE THREAD

**Issue by miendinh** [readium/r2-testapp-js#6]
hi,
I want to build r2-testapp-js on my local but not it is not successful.
Please help to build it, thank you.

I run the following command line:

```
$:~/r2-testapp-js$ node -v
v8.11.3
$:~/r2-testapp-js$ npm -v
5.6.0
$:~/r2-testapp-js$ npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-language-service@0.9.9 requires a peer of typescript@>= 2.3.1 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

moved 2 packages in 28.975s
$:~/r2-testapp-js$ npm run build:all

> r2-testapp-js@1.0.0-alpha.1 prebuild:all /home/mien/r2-testapp-js
> npm run lint


> r2-testapp-js@1.0.0-alpha.1 lint /home/mien/r2-testapp-js
> npm run lint:all && npm run lint:typescript:full


> r2-testapp-js@1.0.0-alpha.1 lint:all /home/mien/r2-testapp-js
> eclint check "**/*" "!**/*.node" "!.git/**/*" "!node_modules*/**/*" "!dist/**/*" "!misc/**/*" "!electron-pack/**/*" "!resources/**/*" "!.vscode/**/*" "!.history/**/*" "!**/.DS_Store" "!**/*.epub" "!**/*.cbz" "!**/*.jpg" "!**/*.jpeg" "!**/*.png" "!**/*.log"

....................

$:~/r2-testapp-js$ npm run start

> r2-testapp-js@1.0.0-alpha.1 start /home/mien/r2-testapp-js
> cross-env DEBUG=r2:* node "./dist/es6-es2015/src/http/server-cli.js" ./misc/epubs/

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/mien/r2-testapp-js/dist/es6-es2015/src/http/server-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2-testapp-js@1.0.0-alpha.1 start: `cross-env DEBUG=r2:* node "./dist/es6-es2015/src/http/server-cli.js" ./misc/epubs/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2-testapp-js@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mien/.npm/_logs/2018-08-12T16_46_43_267Z-debug.log
$:~/r2-testapp-js$

```

**Comment by danielweck** [comment]
Sorry for the late reply, I have just discovered this issue! (I am now "watching" the repository for any future notifications).

Following the other discussions on Slack etc., have you been able to build? From a fresh Git clone of `r2-testapp-js` it should be as simple as:
`npm install && npm run electron`

**Comment by danielweck** [comment]
This is a stale issue (lots of changes in the NPM setup since). Closing.

Also see:
https://github.com/readium/r2-testapp-js/issues/10
